apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3tix
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3tix
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3tix
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3tix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3tix
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nmyo-tenant/rhtap-demo-app/hacbs-test-project-3tix@sha256:0c556a788b8e418c4026e661642287b3c14079b777cfcf9e285a08c0a1028e87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
