apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3tix
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nmyo-tenant/rhtap-demo-app/hacbs-test-project-3tix@sha256:8f0e8f71c568c6cb3aee1a89b5bf6650138c5dd41bc020ab4b2ae37b3a2fbc59
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
